### ISSUE TITLE
How to manage Player States when Recyclerview item change.

### ISSUE THREAD

**Issue by arsalrao** [eneim/kohii#115]
Hi Nam, 
Thank you for providing this.
How can I manage the states of the Player?

When I update the recycler view item like favourite/unfavourite then the video will restart. I need as the video will not restart it keeps playing.

**Comment by eneim** [comment]
@arsalrao Sorry for the late reply. Do you have a tag for your Video? How is the setup looks like for you? How did you do when the change happens? (For example, did you call notifyItemChange or you just call notifyDatasetChange, etc?)

**Comment by arsalrao** [comment]
@eneim Thanks for the reply.

**Do you Have a tag for your Video?**
I'm not using any TAG for video but when I try to set TAG as video URL or any data types then the player did not play any video it throws an exception `com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.android.mpeg4.decoder, Format(1, null, null, video/mp4v-es, null, -1, null, [1280, 853, 29.96836], [-1, -1])`

**How is the setup looks like for your?**
I'm using this in the Nested recycler view as Parent Recyclerview (Vertical orientation) has Child Recyclerview (Horizontal Orientation) so each ITEM of Parent Recyclerview has child recyclerview.
Child Recyclerview Holder has the responsibility to bind all the data.

**How did you do when the change happens?**
I'm doing NotifyItemChange for child recyclerview which is trigger by parent recyclerview adapter.

I made a video about my issue please check it. https://streamable.com/1cj8xr

**Comment by arsalrao** [comment]
@eneim hope you are well and doing great.
any update about this issue?

**Comment by eneim** [comment]
@arsalrao Sorry again, I have some busy weeks so cannot focus on this library. A few points to keep in mind:

- If the ViewHolder is not re-bound, or is re-bound without touching the PlayerView, your setup should be intact (so there should be no reset/restart of the Videos). Please check if your ViewHolder that is bound to the Video is re-bound or not. And what happens if you override the onBindViewHolder method with the payload parameters. Using that to update an existing ViewHolder (e.g. update the favorited/un-favorited one).
- If the whole ViewHolder needs to be re-bound, you need a Tag for the Video so its playback state will be remembered. Actually, I cannot see the relationship between setting the Tag and the error above. But if you can send me a snippet to reproduce it I can take a look.

Since your setup is RecyclerView nested in RecyclerView, If you can replicate the issue using this sample https://github.com/eneim/kohii/tree/dev-v1/kohii-sample/src/main/java/kohii/v1/sample/ui/nested5 it will be really helpful.

Sorry again for the delay. It is understandable if you no longer pick Kohii as it could not give what you want, but if you are sticking around, please let me know. I can restart working on the library somewhere next week and will spend some time for the current issues.

**Comment by arsalrao** [comment]
@eneim I already fixed that issue by updating this item when view is in an invisible state. thanks.
