### ISSUE TITLE
how to know progress for video??

### ISSUE THREAD

**Issue by yongju-jin** [eneim/kohii#14]
Hi, I have a question.
I do not know if this is the right place for the question.
My question is
how can I show my video progress?
I can't find it.

sorry. poor my English. thank you

**Comment by eneim** [comment]
@yongju-jin Do you mean the progress that is calculated by *current position / video duration* ?

Because Kohii is still in alpha, I cannot tell much, though I will eventually put a demo for that use case.

Right now, you can show the progress in the same way **PlayerView** shows the PlayerControlView where there is current position and video position, see [here](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L778).

The concept will be: get current timeline information (position, duration), setup a Handler and execute it every second in a while to update your View that will show that information.

**Comment by yongju-jin** [comment]
thanks for the reply.
and.. I have more question.

1. how to volume control? (mute/unmute)
```kotlin
asPlayable = kohii?.setUp(videoUri)?.asPlayable()
asPlayable?.setVolumeInfo(
    kohii.media.VolumeInfo(              
     )
)
```
error occurred: Unresolved referenced: media

2. can i play video from first when play is completed??
i try
```kotlin
asPlayable?.playbackInfo?.resumePosition = TIME_UNSET
asPlayable?.play()
```

i know Kohii is alpha, but just wanna know Kohii supported
thanks,

**Comment by eneim** [comment]
@yongju-jin 

About the Volume, this is a WIP in my local at the moment. The code base is significantly updated since this alpha actually. Managing volume is quite complicated. Considering Facebook: you mute one Video, all other Videos will be muted. In my latest strategy, I introduce the concept of "change Volume by Scope", which allows client to change volume of a Playback that will also change Volume of others depends on the scope (scope may be everything in the same RecyclerView, or just that one Playback).

The logic works well. But the challenge is to keep that change across config change, which I'm dealing with right now.

About the second question, you can set RepeatMode to the Player instance. I think this alpha doesn't have the method to set the RepeatMode from Playback instance or Playable instance, so you can access to the Player instance from PlayerView instance. My current source code has the method to set this from Playback instance and it will be there in production release.

**Comment by yongju-jin** [comment]
thanks for the reply.
Thanks to Kohii, I finished my work.
thanks for your work.

**Comment by eneim** [comment]
@yongju-jin glad it helps
