### ISSUE TITLE
Migration from jcenter() to mavenCentral() or google()

### ISSUE THREAD

**Issue by pashaoleynik97** [eneim/kohii#168]
Previously I used Toro player for playback implementation. But it hosted on `jcenter()` that is deprecated now. So I decided to migrate to Kohii that is more modern and hosted on `mavenCentral()`.  But latest version of Kohii still using outdated version of exoplayer (2.11.8). This version of exoplayer also hosted on `bintray` ( https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer/2.11.8 ) that also will be disabled soon. And I am not able to permanently remove `jcenter()`.
Do you planning to update Kohii to use new version of exoplayer? E. g. 2.13.3 or newer (that is hosted on `google()`)?

**Comment by eneim** [comment]
@pashaoleynik97 Thanks. I'm aware of that and for at least a year on, you do not need to worry about jcenter being gone (https://developer.android.com/studio/build/jcenter-migration).

Since ExoPlayer 2.14.x is migrated to maven, the upcoming release of Kohii will also be moved to maven. I'm working on some experiment right now and hopefully I can open it really soon. The next update will use ExoPlayer 2.14.2 or 2.15.0 (which was just released and still pretty young).

**Comment by pashaoleynik97** [comment]
Thank you very much for your answer!
