### ISSUE TITLE
Kohii vs Toro and development status

### ISSUE THREAD

**Issue by tabasavr** [eneim/kohii#182]
Hi, I recently started contributing to a project that uses your other project [Toro](https://github.com/eneim/toro). I'd love to update Exoplayer to remove jcenter dependency but both Toro and Kohii use old Exoplayer versions. Kohii looks like a newer project and does basically the same thing as Toro, so I'm posting these two questions here:

1. Is Kohii a replacement for Toro?
2. Are you working on any updates with newer Exoplayer version and/or would you accept pull requests to either repo?

**Comment by eneim** [comment]
@RSBat Sorry for the late reply:

> Is Kohii a replacement for Toro?

Yes, you can think so. Any new project wants to consider between them should use Kohii.

> Are you working on any updates with newer Exoplayer version and/or would you accept pull requests to either repo?

Yes I'm trying to update the library to the new ExoPlayer version. I should be more aggressive on this because I think many is waiting for it. My current issue are time and the amount of change ExoPlayer brings. Let me set a goal to publish the new release by the end of this month or as late as the first week of Sep.

**Comment by tabasavr** [comment]
> > Are you working on any updates with newer Exoplayer version and/or would you accept pull requests to either repo?
> 
> Yes I'm trying to update the library to the new ExoPlayer version. I should be more aggressive on this because I think many is waiting for it. 

Great, I'm glad it is not abandoned 

> My current issue are time and the amount of change ExoPlayer brings. 

At least for me updating just to 2.13.3 would be enough because it is the first version available in Google's maven repository. And the amount of changes is not as big as updating to the latest version. 

> Let me set a goal to publish the new release by the end of this month or as late as the first week of Sep.

Sure, no pressure

**Comment by eneim** [comment]
Hey, FYI it is a bit later than plan but I finally release a new version with ExoPlayer 2.17.1. Tried to make it for 2.14.x but many thing doesn't build successfully.
