### ISSUE TITLE
How can i use PlayerControlView in kohii

### ISSUE THREAD

**Issue by Diegofr104** [eneim/kohii#45]
Im trying to add the controller bar at bottom of playerview but nothing happens, i tryed to use inside of playerview just using controller_layout_id and then tryed another way using PlayerControlView  and nothing happned on both and i cnat see the bar. 
I need to implement something different?

**Comment by eneim** [comment]
@Diegofr104 Assuming that you are using B0 or some Alpha, Kohii will hide any controller by default. The reason is by default, Kohii enforce automatic playback, therefore no manual control should be allowed, or else user will experience weird things like: He/She paused the video before, then scroll up, then scroll down, then the Video will resume without his/her control, which is weird.

---

To enable manual control, in B0 and latest B1, you can do as follow:

```Kotlin
// Below is the call format of B0, doesn't apply for alpha release
kohii.setUp(videoUri) {
  controller = // require a `Controller` object here.
}.bind(playerView)
```

Though the design for manual playback is not fully done yet. The reason is quite long, but in short, the control flow is quite complicated, especially in case of RecyclerView where a PlayerView can be recycled to be reused in other Video.

---

To summary, please give me more information about your overall flow: how would you imagine the manual playback would be? do you want mixed manual/auto playback or just full manual playback where User needs to start/pause by himself/herself all the time? what if the started Video is scrolled off-screen, should it keeps playing or will be paused (*automatically*)?

These are also the questions I'm asking myself to design a reasonable interface for manual playback. So if you are serious about this, please help to give some ideas. Thanks.

**Comment by Diegofr104** [comment]
Thx for answer, i hope you are fine!, i will answer your questions one by one.

1-how would you imagine the manual playback would be?

I imagine the manual playback simple UI like  play/pause behavior in the controller, seekbar and time left, if you scroll to the next one the previous video time need to be store for reuse again if you go back again to the previous video and resume from where you was previously.
If you pause a video and you scroll i think the state of "paused" will be reset to play from where it was when was paused.

2-do you want mixed manual/auto playback or just full manual playback where User needs to start/pause by himself/herself all the time?

I want mixed playback, the videos start automatically but if controller is enabled (by default will be disabled),user can interact with the controller, if the video is off-screen video will be paused and will be nice that this video can be resumed at the state it was previously.

3-what if the started Video is scrolled off-screen, should it keeps playing or will be paused (automatically)?
If is completely off-screen need to be paused automatically, if not keep playing.

If you need more ideas i will be here for help, im really serious about this, and needed that functionality, your library is awesome!, if i can help in other thing like coding i will be available(Im new in this video playback thing so my knowledge is limited but i can help in whatever i can).

Thank you again!.

**Comment by eneim** [comment]
@Diegofr104 Please try this setting in your `setUp`

```kotlin
val manager = kohii.register(this).addBucket(container) // this is API from B1
kohii.setUp(videoUri) {
      tag = // you need a unique tag here
      controller = DefaultControlDispatcher(
          manager, playerView,
          kohiiCanStart = true,
          kohiiCanPause = true
      )
    }
        .bind(playerView)
```

It should work with your case. Though the design still has some issues that cannot cover enough edge case (not this case). Make sure to update to B2 because B1 has some dependency issues. Also the argument for the call to `bind` must be a `PlayerView` or its subclass.

**Comment by Diegofr104** [comment]
I tryed what you suggest and works fine!. 
I have another question, it is possible to use the controller outside the PlayerView? like PlayerControlView.

**Comment by eneim** [comment]
@Diegofr104 It is not supported now. What do you want? One PlayerControlView for many PlayerView or still one PlayerControlView for one PlayerView?

**Comment by Diegofr104** [comment]
Oh ok its fine.
Ithink the best approach is one PlayerControlView for many PlayerView.

**Comment by eneim** [comment]
@Diegofr104 Well I have not clearly double check, but you can try the follow implementation:

Have your Fragment or Activity (whichever contains your Videos) implement `OnSelectionListener` and in `fun onSelection(selection: Collection<Playback>)` add the following:

```Kotlin
  // Note that I use ViewBinding here so there is 'binding' object. You can just use your own way.
  // Below code is done for NestedScrollView as the container for Videos, not RecyclerView.
  // binding.controlView is the global PlayerControlView.
  override fun onSelection(selection: Collection<Playback>) {
    val playback = selection.firstOrNull()
    if (playback != null) {
      binding.controlView.showTimeoutMs = -1 // non-positive so it will never hide
      binding.controlView.show()
      val container = playback.container
      if (container is PlayerView) {
        container.useController = false // if you want to only use the global controller.
        binding.controlView.player = container.player // sync the Player state
      }
      val controller = playback.config.controller
      if (controller is ControlDispatcher) {
        binding.controlView.setControlDispatcher(controller) // re-use the controller, and important to also have Kohii logic behind.
      }
    } else {
      // clear everything
      binding.controlView.setControlDispatcher(null)
      binding.controlView.player = null
      binding.controlView.hide()
    }
  }
```

Though I did not fully confirm this against RecyclerView, it should work. The point here is `onSelection` will be called every time the selection happens, even if nothing is changed. So you can have some optimization on your own. I will see if this scenario can be done better, but it will be lower priority than other of my TODOs.

**Comment by Diegofr104** [comment]
Thank you @eneim it works!.

Im very grateful for all the help you give to me, when i finish my project and get the investors i will compensate you for that, i promise you :).

**Comment by eneim** [comment]
@Diegofr104 It is great that Kohii can help you. As said the manual control is still under designing phase and your input was truly helpful. If your service succeeds and you have the will to compensate, I will be grateful. So good luck. 

I will close this issue, if you have any other trouble let's open new one.
